### ISSUE TITLE
How to unify the coordinate system between sfm model and BIM model?

### ISSUE THREAD

**Issue by lck666666** [debaditya-unimelb/RecurrentBIM-PoseNet#1]
In your dataset, it consists both real images and synthetic images. Real images can get pose label from SfM tools, and synthetic images can get pose label from BIM model. But how to unify the coordinate system between sfm model and BIM model?

**Comment by lck666666** [comment]
And what software did you use to get the label for synthetic images.

**Comment by debaditya-unimelb** [comment]
The BIM coordinate system and SfM coordinate system were manually aligned. Uniquely identifiable markers (around 25) coordinates were measured using BIM-vision and were entered in AGISoft Pro Photoscape which did the registration, and we kept the RMS error under a few centimeters. 

We used Blender to generate the synthetic images and to export the labels of the synthetic images. Let me know if you would be interested in having the Blender file with python code to generate the synthetic images, and the trajectory as well.
